Change hard-coded headernames to lowercase
http-rs/http-types pull request #386
Opened 2021-10-30 18:27 UTC by halvko

The change at line 114 in `src/security/mod.rs` corrects a logic error, the rest is at best a small optimization and at worst a style choice

2022-01-25 11:15 UTC, yoshuawuyts requested changes
I'm not sure I understand what issue this solves? Header names should be case-agnostic. And since we're only ever encoding values here, if an error occurs it seems like the issue would be in a parser, not in any of the encoders?

I feel like I'm missing something?

2022-01-25 12:45 UTC, halvko commented
As I understand it, headers are not case agnostic for HTTP/2 connections “However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2” (https://httpwg.org/specs/rfc7540.html#HttpHeaders).

2022-01-25 12:48 UTC, halvko commented
And the documentation for ‘headername::from_lowercase_str’ specifically states that the input is expected to be lowercase

2025-05-12 05:36 UTC, halvko commented
I'll close this as it's old and no interest was shown in merging it

2025-05-12 05:36 UTC, closed without merging